spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update
# h2 connection info
  datasource:
    url: jdbc:h2:mem:sample
    driverClassName: org.h2.Driver
    username: markkang05
    password:
  h2:
    console.enabled: true
    console.path: /h2-console